### ISSUE TITLE
当在页面的标签头上进行切换时会产生两个相同的页面

### ISSUE THREAD

**Issue by cloonist** [d2-projects/d2-admin-ice#2]
用ICE上的D2admin ICE 1.4.4版本模板生成的项目上，再用ICE生成新的页面加入项目，用对应的菜单打开新建的页面，然后点击首页标签切换到首页，再点击前面打开的页面的标签切换到该页面，这时会多出一个重复的标签页。奇怪的是，如果是模板自带的两个Demo页无论怎么切换都不会出现这样的问题，但用ICE生成的新页面一定会出现这样的BUG
我使用的ICE是Mac下的ICE 2.22.0版本

**Comment by FairyEver** [comment]
应该是飞冰生成策略调整导致的问题。

修改方法 https://github.com/ice-lab/vue-materials/pull/19/files
